### ISSUE TITLE
Displays View in Tooltip text of the delete/remove btn.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/expcon.in#110]
![image](https://user-images.githubusercontent.com/46882833/66738020-1dd6ec00-ee8b-11e9-8b52-5a3ee3f8060e.png)

**Comment by risipatel** [comment]
### Team Tab of Company Page.
![image](https://user-images.githubusercontent.com/46882833/67143254-38dc9e00-f287-11e9-8154-ebcf7d06e731.png)

**Comment by ajayrajecb** [comment]
### 1. Display tool-tip text "Leave Company"
### 2. In popup show label 'Last Working day' above date text box.
![2019-10-21_12-53-08](https://user-images.githubusercontent.com/46882964/67184693-ebd10700-f401-11e9-86a0-d3d00b28ef63.png)

**Comment by risipatel** [comment]
## Unsolved
> 
> ### 1. Display tool-tip text "Leave Company"
> 
> ![2019-10-21_12-53-08](https://user-images.githubusercontent.com/46882964/67184693-ebd10700-f401-11e9-86a0-d3d00b28ef63.png)
