### ISSUE TITLE
On click of Invites tab space gets added between text and count.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/expcon.in#111]
### On Page Load
![UiIssue](https://user-images.githubusercontent.com/46882833/66739477-680d9c80-ee8e-11e9-9e47-1248b05a728f.png)

### On Click of Invite Tab
![UiIssue1](https://user-images.githubusercontent.com/46882833/66739478-68a63300-ee8e-11e9-9915-8671c87d8823.png)

**Comment by risipatel** [comment]
### And Need to change Contacts Details to Contact Details.
![UiIssue2](https://user-images.githubusercontent.com/46882833/66739771-0bf74800-ee8f-11e9-9e11-c587ef80aa0f.png)

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/76729255-b21ce600-677e-11ea-9734-dfc1d60031a6.png)
