### ISSUE TITLE
Need to add few details in verfiy email content. 

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/expcon.in#150]
Need to tell user that this verification mail is for this company or this member.
![image](https://user-images.githubusercontent.com/46882833/67140804-e9dd3b80-f27b-11e9-944b-15f79ec181cc.png)

**Comment by risipatel** [comment]
Need to correct spelling of Purpose.

**Comment by risipatel** [comment]
Will give you mail content.

**Comment by dharmendraecb** [comment]
mail content change.
