### ISSUE TITLE
Redirects user to a URL where Cid is missing.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/expcon.in#167]
**Steps to Reproduce:-**
1. Go to edit mode of company.
2. Click on any Textbox in Contact Details Tab.
3. Now press enter on keyboard.
![image](https://user-images.githubusercontent.com/46882833/67205096-98c07980-f42c-11e9-9ef8-f882a51038b5.png)

**Comment by dharmendraecb** [comment]
profileedit page And companyedit page  error Fixed.
