### ISSUE TITLE
Slider text should be start with center 

### ISSUE THREAD

**Issue by jayshah6777** [EasyCloudConsultants/expcon.in#197]
![image](https://user-images.githubusercontent.com/58812881/70983783-555a5280-20df-11ea-99c3-da6f0ba4ef99.png)

1) slider text start with center 
2)auto manage in center it's looking good

**Comment by Avinash-ecb** [comment]
done in theme 2 ,theme 3 and in theme 4 I did not do because every theme slider should not same

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/71234872-61812280-2320-11ea-8aba-a847189b5d2b.png)

1) textbox issue on chrome browser 
2) on fire fox running properly

**Comment by Avinash-ecb** [comment]
done in theme 2 ,theme 3 and in theme 4 I did not do because every theme slider should not same
