### ISSUE TITLE
Edit functionality of company profile photo not working 

### ISSUE THREAD

**Issue by jayshah6777** [EasyCloudConsultants/expcon.in#198]
![image](https://user-images.githubusercontent.com/58812881/70996868-b7c04c80-20f9-11ea-93a9-375549635d0b.png)

1) company profile photo not showing on company profile page
2) it is showing on company profile photo on company detail page

**Comment by risipatel** [comment]
#### When user updates his profile pic for the first time then Expcon doesn't reflect updated picture. To see updated picture user requires to re-login. 
![image](https://user-images.githubusercontent.com/46882833/71167999-cb93bc00-227b-11ea-9745-9d22ecd77531.png)
