### ISSUE TITLE
company profile photo require hard reload

### ISSUE THREAD

**Issue by jayshah6777** [EasyCloudConsultants/expcon.in#206]
![image](https://user-images.githubusercontent.com/58812881/71400311-64478480-264c-11ea-8dbd-f77a1e7f22f8.png)

1) company profile photo update on edit firm page
2) company detail page on not showing profile photo
3) after hard reload show profile photo

![image](https://user-images.githubusercontent.com/58812881/71400441-cd2efc80-264c-11ea-806f-caf6b9ca1f5f.png)

**Comment by dharmendraecb** [comment]
images upload hone me time lagta he.
