### ISSUE TITLE
need to change service functionality 

### ISSUE THREAD

**Issue by jayshah6777** [EasyCloudConsultants/expcon.in#251]
![2020-01-21_1233](https://user-images.githubusercontent.com/58812881/72782641-4b7dbf00-3c4a-11ea-803a-c0202d5d9480.png)

1) when price 0 and days 0. price and days should not show
2) when price 0.  price and days should not show
3) when price min 1RS and days 0.  price and days should show

**Comment by Avinash-ecb** [comment]
Fixed in company theme only
