### ISSUE TITLE
Timing field replicates selected time on click of Save.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/expcon.in#26]
**Steps To Reproduce**

1. Go to Edit Profile.
2. Now Select time.
3. Then click on Save button multiple times.

![image](https://user-images.githubusercontent.com/46882833/64152808-fe3fb300-ce4a-11e9-8a70-6781c94e4ff1.png)

**Comment by dharmendraecb** [comment]
Profile Edit in this functionality remove.
