### ISSUE TITLE
need to fix character length service and package name on company edit  

### ISSUE THREAD

**Issue by jayshah6777** [EasyCloudConsultants/expcon.in#271]
![image](https://user-images.githubusercontent.com/58812881/73166667-4920d680-411c-11ea-9b3b-c208fe75cee9.png)

![image](https://user-images.githubusercontent.com/58812881/73166885-c2b8c480-411c-11ea-978a-615e72ddc106.png)

![image](https://user-images.githubusercontent.com/58812881/73238012-707bb000-41bd-11ea-933a-f54f64ebd7d2.png)

**Comment by dharmendraecb** [comment]
maximum 50 char allow.
