### ISSUE TITLE
Doesn't allows user to invite branch even if that company dont have any invitation.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/expcon.in#274]
### Rishi Infotech
![image](https://user-images.githubusercontent.com/46882833/73239076-1381f900-41c1-11ea-8aaf-f2367fe97609.png)
### Test Pvt Ltd.
![image](https://user-images.githubusercontent.com/46882833/73239130-3f04e380-41c1-11ea-8332-d03876cbb6b4.png)

**Comment by risipatel** [comment]
Not able to test because of #288

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/76184831-550bb800-61f3-11ea-8ea9-80f946961c1f.png)

Solve test by jay

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/76209712-8baff580-6228-11ea-8e13-f87c6aee7073.png)
