### ISSUE TITLE
Do we need box on Username?

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/expcon.in#28]
@vinpahilwani 
![image](https://user-images.githubusercontent.com/46882833/64168632-951b6800-ce69-11e9-9968-abbb78430ea3.png)

**Comment by vinpahilwani** [comment]
right approved

**Comment by risipatel** [comment]
Remove that box. @dharmendraecb

**Comment by risipatel** [comment]
![image](https://user-images.githubusercontent.com/46882833/64904087-2ac4bc00-d6e2-11e9-8ea0-803a1c50f1cb.png)
