### ISSUE TITLE
User not get image link on email 

### ISSUE THREAD

**Issue by jayshah6777** [EasyCloudConsultants/expcon.in#286]
![image](https://user-images.githubusercontent.com/58812881/73590885-fd03d680-450d-11ea-9f5c-b948206576b9.png)

![image](https://user-images.githubusercontent.com/58812881/73590914-43593580-450e-11ea-8782-17646b7f51ee.png)

1) User not get image,xlx link on gmail

**Comment by dharmendraecb** [comment]
subject new field.
