### ISSUE TITLE
Same theme on two different company  but not showing proper FACTS 

### ISSUE THREAD

**Issue by jayshah6777** [EasyCloudConsultants/expcon.in#349]
![image](https://user-images.githubusercontent.com/58812881/75416708-16edd900-5955-11ea-9713-6e959e0b87f9.png)

1) Same theme on two different company  but not showing proper FACTS 

![image](https://user-images.githubusercontent.com/58812881/75416743-31c04d80-5955-11ea-9bd3-cee402ff6238.png)

**Comment by Avinash-ecb** [comment]
wicasa vadodara is institute so it will not show facts as vinod sir told me

**Comment by jayshah6777** [comment]
Okay
