### ISSUE TITLE
Create view of About me is different than Edit view of it.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/expcon.in#35]
### Create View
![image](https://user-images.githubusercontent.com/46882833/64228829-add95b80-cf05-11e9-8339-97b14bcb39da.png)
### Edit View
![image](https://user-images.githubusercontent.com/46882833/64228856-c47fb280-cf05-11e9-90b2-d37a27757e5b.png)

**Comment by vinpahilwani** [comment]
ive discussed with dharmendra to show both title and description on same page in edit view

**Comment by risipatel** [comment]
Functionality has changed..
![image](https://user-images.githubusercontent.com/46882833/64906866-121bcc80-d709-11e9-8e76-4287c154ff0e.png)
