### ISSUE TITLE
Experience and Education should be displayed as Timeline.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/expcon.in#37]
If we display Education and Experience in ascending order then it can be used as Timeline.  As of now it is being displayed as it has been inserted. @vinpahilwani 
![image](https://user-images.githubusercontent.com/46882833/64231965-92268300-cf0e-11e9-866c-07d362aafe4d.png)

**Comment by vinpahilwani** [comment]
latest upar aana chahiye and then uske baad wala experience

**Comment by risipatel** [comment]
Sorts according to "From Date" only. If From date is same then need to check To date of those records.

**Comment by risipatel** [comment]
Leave it as of Now.. -On Behalf of Vinod Sir
