### ISSUE TITLE
Edit Firm - Software

### ISSUE THREAD

**Issue by camanojsahu87** [EasyCloudConsultants/expcon.in#46]
Getting error screen shot attac
![image](https://user-images.githubusercontent.com/54883293/64326491-af7b5000-cfe7-11e9-8798-aad235fe172a.png)
hed

**Comment by risipatel** [comment]
Displays above message when user selects software from suggestion drop down. Allows to add only if the entered name in not present in entire database. @dharmendraecb 
![image](https://user-images.githubusercontent.com/46882833/64849674-82efb580-d631-11e9-9956-6c0133e2e724.png)
