### ISSUE TITLE
Not able to add affiliation in My Company

### ISSUE THREAD

**Issue by camanojsahu87** [EasyCloudConsultants/expcon.in#54]
![image](https://user-images.githubusercontent.com/54883293/64491512-fb97f000-d286-11e9-883d-cbead7fc2b04.png)

**Comment by risipatel** [comment]
Now its working.. #38 @camanojsahu87 
![image](https://user-images.githubusercontent.com/46882833/64864227-46818100-d654-11e9-98dc-0969d0af5386.png)
