### ISSUE TITLE
Displays member in Staff list even after rejecting invitation.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/expcon.in#69]
**Describe the Bug**
Expcon displays member in staff list in following situation
1. Even when Member rejects invitation from Company.
2. Or even when Company rejects invite from Member.

### Scenario 1
**Edit Mode of Member**
![image](https://user-images.githubusercontent.com/46882833/64768244-b87b9c80-d566-11e9-8977-466ed1af947a.png)
**View Mode of Company**
![image](https://user-images.githubusercontent.com/46882833/64768226-b1ed2500-d566-11e9-8dce-b07dd5eefab1.png)

### **Scenario 2**
**Edit Mode of Company**
![image](https://user-images.githubusercontent.com/46882833/64767901-2ffcfc00-d566-11e9-85d6-2157f052c8fd.png)
**View Mode of Company**
![image](https://user-images.githubusercontent.com/46882833/64768342-e82aa480-d566-11e9-9484-3815705922aa.png)

**Comment by risipatel** [comment]
If invitation gets rejected then expcon should remove member from view mode of company and member. And in edit mode keep it as it is. @vinpahilwani

**Comment by risipatel** [comment]
### Member Profile View in both Scenarios
In Ajay Associates mr Robin has rejected invitation.
And in Rishi Infotech company has rejected invitation.
![image](https://user-images.githubusercontent.com/46882833/64853220-97837c00-d638-11e9-8440-03c904538151.png)

**Comment by vinpahilwani** [comment]
approved
